### ISSUE TITLE
Visibility of imported "IODD files" 

### ISSUE THREAD

**Issue by Rajkumarpulaparthi** [TINF17C/ModellingWizard#10]
imported IODD files can only access through AutomationML "open AML Container". But these files are not visible in the directory as created files.

**Comment by DorianSnowball** [comment]
I does not exactly get what the problem is.
Can you describe it a bit more?

**Comment by Rajkumarpulaparthi** [comment]
".AMLX files" created after importing "IODD files" can only accessible
through File > open > open AML container.(This is working)

Now,  #close the AML Editor application. "Open through the file"

They were not found while we search in the location they were stored in
(not through AML Editor). Due to this, I cannot find the file .AMLX to
transfer to other location or to share the file.
