### ISSUE TITLE
Missing "Icons" .

### ISSUE THREAD

**Issue by Rajkumarpulaparthi** [TINF17C/ModellingWizard#9]
1. After the start of the "Modelling wizard" plugin, "Floating" option has to be selected to make the "Icons" visible every time. where starting of plugin stays always in "dockable". 

2. In "dockable".
![image](https://user-images.githubusercontent.com/50583292/58868283-47516100-86bc-11e9-9ccd-09900c0b119e.png)

3. after selecting "Floating".
![image](https://user-images.githubusercontent.com/50583292/58868343-6819b680-86bc-11e9-8498-847a664cde92.png)

**Comment by DorianSnowball** [comment]
This is a bug caused by the AML Editor Window Manager.
If you select another Theme for the editor, everything works fine.
I should update the readme to warn about this case.
